CREATE USER '6vtvpeodz3zlo_stg'@'%' IDENTIFIED BY 'staging123456';

GRANT SELECT, INSERT, UPDATE, DELETE,
      CREATE, DROP, INDEX, ALTER,
      CREATE TEMPORARY TABLES, LOCK TABLES,
      EXECUTE, CREATE VIEW, SHOW VIEW,
      CREATE ROUTINE, ALTER ROUTINE, TRIGGER
ON oxxoep.* TO '6vtvpeodz3zlo_stg'@'%';

FLUSH PRIVILEGES;
