mysql:
  image: mariadb:10.4
  command: 
    - --default-authentication-plugin=mysql_native_password
    - --character-set-server=utf8
    - --collation-server=utf8_general_ci
    - --innodb-buffer-pool-size=1G
  volumes:
    - ./db:/var/lib/mysql/
    - ../services_logs/mysql:/var/log/mysql/
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=mysql
  container_name: mysql
  restart: always
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  environment:
    - PMA_HOST=mysql
    - MYSQL_ROOT_PASSWORD=mysql
  links:
    - mysql
  ports:
    - 8080:80
  container_name: phpmyadmin
  restart: always
